---
- name: run rancher
  shell: docker run -itd --restart=always --name "{{ rancher_name }}" -v "{{ rancher_data }}:/var/lib/rancher"   -p "{{ rancher_port }}:80" -p "{{ rancher_ssl_ports }}:443"  "{{ rancher_image }}"

- name: wait rancher start
  shell: sleep 20

- name: rancher url
  debug: msg="You can connect to rancher server http://{{ ansible_ssh_host }}:{{ rancher_port }}"

- name: login using default password
  uri:
    url: '{{ rancher_url }}/v3-public/localProviders/local?action=login'
    method: POST
    body: {"username":"admin", "password":"admin"}
    status_code: 201
    body_format: json
    validate_certs: "{{ validate_certs }}"
  register: login_result
  until: login_result.status == 201
  retries: 3
  delay: 10
  ignore_errors: true


- name: Change the password
  uri:
    url: '{{ rancher_url }}/v3/users?action=changepassword'
    method: POST
    body: {"currentPassword":"admin", "newPassword":"{{ rancher_admin_password }}"}
    headers:
      Authorization: "Bearer {{ login_result.json.token }}"
    body_format: json
    validate_certs: false
    status_code: 200
  when: login_result.status in [201]

- name: Get response from login endpoint using non default password
  uri:
    url: '{{ rancher_url }}/v3-public/localProviders/local?action=login'
    method: POST
    body: {"username": "admin", "password": "{{ rancher_admin_password }}"}
    status_code: 201
    body_format: json
    validate_certs: "{{ validate_certs }}"
  register: login_result
  until: login_result.status == 201
  retries: 10
  delay: 10


- name: Create api key 
  uri:
    url: '{{ rancher_url }}/v3/token'
    method: POST
    body: {"current":false, "expired":false, "isDerived":false, "ttl":86400000, "type":"token", "description":"automation"}
    status_code: 201
    body_format: json
    headers:
      Authorization: "Bearer {{ login_result.json.token }}"
    validate_certs: "{{ validate_certs }}"
  register: api_key_result

- name: echo login_result.json.token
  debug: msg="{{ login_result.json.token }}"

- name: Set rancher server rul
  uri:
    url: '{{ rancher_url }}/v3/settings/server-url'
    method: PUT
    body: {"name":"server-url","value":"{{ rancher_url }}"}
    headers:
      Authorization: "Bearer {{ api_key_result.json.token }}"
    status_code: 200
    body_format: json
    validate_certs: "{{ validate_certs }}"
