---
- name: install required packages
  yum: name={{ item }}   state=present            
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: add docker repo
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  register: result        

- name: install docker
  yum: name=docker-ce state=present
  when: result.rc ==0
  register: docker

- name: start docker
  systemd: name=docker state=started enabled=yes
  when: docker.rc ==0
